### PR TITLE
Move updated cookie js to campaign profile

### LINKED ISSUE #1443: Cookie banner updates for GDPR
Investigate how we handle cookie banner and cookie storage across all our site.

### PR DESCRIPTION
**Pull request by AndyEPhipps**
Type: patch

Fixes #1443

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
QA-able here, all existing CR.com cookie functionality ported over to campaign base:

https://pr-1487-gqahgyy-tx3mbsqmxtu74.eu.platform.sh/fundraise

**Comment by KrupaPammi** [comment]
> QA-able here, all existing CR.com cookie functionality ported over to campaign base:
> 
> https://pr-1487-gqahgyy-tx3mbsqmxtu74.eu.platform.sh/fundraise

@AndyEPhipps have tested this, just like to mention cookie banner is covering the header menu completely on devices and slightly on desktop browsers.

**Comment by AndyEPhipps** [comment]
@KrupaPammi - ahh this wasn't supposed to be formally QA'd; we have limited styles for Campaign Base itself, and there's not much point spending time fixing it in a non-public site (I think it already looked like that). BUT, I **will** get you to QA the updates within CR and SR  for sure  :)

**Comment by KrupaPammi** [comment]
> @KrupaPammi - ahh this wasn't supposed to be formally QA'd; we have limited styles for Campaign Base itself, and there's not much point spending time fixing it in a non-public site (I think it already looked like that). BUT, I **will** get you to QA the updates within CR and SR for sure :)

cool, thought so @AndyEPhipps just wanted to double check. This has passed QA

**Pull request merged**
