### PR TITLE
Automate changelog in the releases

### LINKED ISSUE #1054: Automate changelog in the releases
We want to make it easier to the release manager the process of the release.

In order to achieve that we need to improve our PR formats, I created a script that shows the commits from the last release. You can try this script in your local (it's harmless).

If someone thinks that would be more clear this change/updating some docs/templates let me know please!

### PR DESCRIPTION
**Pull request by Saphyel**
Fixes #1054 

## Changes proposed in this PR

- Help release manager
- Improve our PR title readability

### CODE REVIEW

**Comment by pvhee** [comment]
@Saphyel could you show an example of such a generated release log?

**Comment by Saphyel** [comment]
@pvhee 
```
. .github/release_script.sh 
**Changelog** (since [1.31.1...1.31.2](1.31.1...1.31.2))

- 1051: removing Drupal styling to be added to PL (#1053)
- 1035 Update Entity Browser (#1047)
- 1044 alter gtm script (#1048)
- Fix markdown table in CR Article README (#1049)
- 1044 - Make alterations to GTM script (#1046)
- Add blog posts to main README (#1045)
- 1042 - Change array structure of news view filter (#1043)
- 1038 Update Embed (#1041)
- 1037 Update Paragraphs (#1039)
- 1015 add classes and fix filters press releases (#1031)
- campaign-1033 Update Token (#1036)
- 1032 Update Scheduled Updates (#1034)
- Fix 1029 Update Search API (#1030)
- 1027 Update ImageMagick (#1028)
- Fix 1025 Update Drupal core (#1026)
- Fix #1024 update publish date for avoid random sorts (#1023)
- Update CDN module to version 3.1 (#1022)
- Merge pull request #1021 from comicrelief/feature/#1020_add_missing_menu_class_to_template
- 1020: adding missing class thats already used in PL styles
- Merge pull request #1019 from comicrelief/1018_behat_fix
- #1018 Fix test
- #1018 Fix behat test
- Merge pull request #1017 from comicrelief/1016_logo_override
- 1016: added auto margin right to logo
- 1016: removed position absolute from logo
- 1012 - Add news type to articles without article type (#1013)
- Merge pull request #967 from comicrelief/929_navigation_modules
- 929: adding Smartmenu as theme lib, rather than concatting into theme JS
- 875 update news path pattern (#978)
- 1008 - Change colour service methods to protected (#1009)
- 929: updated pattern-lab version number
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Fix badge URLs in README
- Fix travis.yml (#1007)
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 929: added lines to close menu when clicking next to menu or on one of the meta icons
- Use Travis CI .org rather than .com
- 870 article cat optional (#973)
- 922 Change RabbitMQ message format and queue (#1005)
- 920 Add badges (#977)
- Merge branch '929_navigation_modules' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 929: removed line of js that's already done in pattern-lab
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 979 - Allow null categories for feature articles (#1004)
- 995 - Add button colours method to colour service (#1006)
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 990 Update ds config (#991)
- #1001 Update names (#1002)
- #999 Upgrade Core to 8.3.4 (#1000)
- 929: removed cr_navigation module from cr.info file as it shouldn't be enabled by default
- 929: removed js library from module as the feature items are created through the template
- 929: moved hamburger button up in markup and wrapped featured items and feature nav hamburger button in div
- 929: added markup for featured items in feature nav block template
- 929: changed some classnames in nav templates
- Update cr.install
- Merge pull request #994 from comicrelief/993_remove_composer_deploy
- 993 Remove from composer.json
- 993 Remove composer deploy module
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Merge branch '929_navigation_modules' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 929: class and documentation updates
- Merge branch '929_navigation_modules' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Merge pull request #992 from comicrelief/982_remove_panels
- 929: updated class names
- 929: new hook to provide control over menu block template also
- Merge branch '929_navigation_modules' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 929: info updates to repurposed nav module
- Merge branch '929_navigation_modules' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- 929: theme suggestion hook and new feat nav template
- 982 Remove panels module from codebase
- 876 - update basic full editor values (#972)
- 985 Reduced wait time (#986)
- 916 Update twig extension related modules (#988)
- Merge pull request #971 from comicrelief/970_postcss_setup
- 970: remove unnecessary npmloadtask call
- 916 upgrade core to 8.3.x (#945)
- 929: importing nav js from PL
- 929: correct typo in nav JS selector
- 974 Fix submit button ID (#980)
- 929: added smartmenus package as we can't import directly from PL version
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- Merge pull request #976 from comicrelief/975_fix_config
- 975 fix config issues
- #928 - updated search for pdf file (#955)
- 970: updated lockfile
- 970: adding PostCSS to build processes
- Fix #968 move config files (#969)
- Merge branch 'develop' of https://github.com/comicrelief/campaign into 929_navigation_modules
- #929 commented out the nav module for testing
- #929 changed the hamburger menu button selector to be more generic to function for both main and feature nav
- #929 added js from pattern-lab components to grunt concat job
- #929 updated templates for new main nav
- 867 - Add patch to fix messy urls issue (#952)
```

**Comment by pvhee** [comment]
@Saphyel sounds good -- this might need to be manually pruned e.g. to take out things like `Merge pull request #976 from comicrelief/975_fix_config` (if we squash&merge we shouldn't have this anyways).

**Comment by Saphyel** [comment]
@pvhee yes, that's because some people used merge pull request.. if in the future everyone squash & merge, you'll get very clean ones like: `Fix travis.yml (#1007)` or `Add blog posts to main README (#1045)` 

Update the title and use squash & merge takes no time if everyone does it

**Comment by pvhee** [comment]
@Saphyel still needs some doc on how to use this before we can merge this in

**Pull request merged**
