### PR TITLE
1228 - add large variation to single msg

### LINKED ISSUE #1228: Single message row additional variations
https://github.com/comicrelief/sr18/issues/20

### PR DESCRIPTION
**Pull request by gusliedke**
Fixes #1228

### CODE REVIEW

**Comment by gusliedke** [comment]
@JamesSquire @alexjohnston266 Leigh . https://pr-1229-xzqhczy-tx3mbsqmxtu74.eu.platform.sh/fundraise . We have Copy Only Large and Small (8 and 10 columns). Does it work for you?

**Comment by JamesSquire** [comment]
@gusliedke I believe we wanted the option to have 6 or 8 columns, not 8/10. Currently/previously, we were limited to 6, I believe.

**Comment by gusliedke** [comment]
I thought copy only variation was 6 columns but it is actually 8 columns desktop, 10 tablet and 12 phone. I made it to have the option to keep 8 (small) and 10 (large). behaving the same in tablet and phone. Did you look the environment with an example? What do you think?

**Comment by CarolineRennie** [comment]
@JamesSquire this is blocked awaiting design review - can you confirm is the PR is correct?

**Comment by JamesSquire** [comment]
Sorry, @CarolineRennie. 😇

The examples seem to have disappeared from the link that Gus originally provided. Could we possibly have another look? I'll make sure to check it out today if so. 💕💕💕💕💕💕💕💕

**Comment by gusliedke** [comment]
@JamesSquire it's back on https://pr-1229-xzqhczy-tx3mbsqmxtu74.eu.platform.sh/fundraise

**Comment by JamesSquire** [comment]
Looks good! I think my understanding of the grid is a little wrong - I'll try to rectify that.

If the current is technically 8 (and not 6) columns, having the option for 10 would be the ideal. 

Thumbs up from me!

**Pull request merged**
