### PR TITLE
1153 js updates search and esu buttons

### LINKED ISSUE #1153: JS updates for new ESU and Search buttons

### PR DESCRIPTION
**Pull request by AndyEPhipps**
Fixes #1153

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
@gusliedke @Heleen-cr: tested locally, not sure if CR.com will need these template updates too - if so, plz put them in... or wait for me to get back?

**Comment by gusliedke** [comment]
Why `composer.lock` is different? Yes we need to move those twig files to other campaign projects too.

**Comment by adamclark-dev** [comment]
@gusliedke the changes in the composer.lock are fine, no packages are changed by the updates.

**Comment by gusliedke** [comment]
ok, I will create a ticket on CR for updating campaign and remind to update the twig files as well.. merging this one.

**Pull request merged**
