### PR TITLE
Remove crazyegg

### LINKED ISSUE #1191: Remove crazyegg
We don't need it

### PR DESCRIPTION
**Pull request by Saphyel**
Fixes #1191

No changes

### CODE REVIEW

**Comment by pvhee** [comment]
@Saphyel can you check with Hiral to see if we still require a separate module for CrazyEgg, as I believe we might be loading this through GTM?

**Comment by Saphyel** [comment]
Block until monday

**Comment by pvhee** [comment]
@Saphyel looks good, but how will we manage the uninstall of this module in e.g. rnd.com ?

**Comment by Saphyel** [comment]
That's config of the site, so needs a pre-release .. in CR we are not using it

**Pull request merged**
