### PR TITLE
Update build file and theme to use Yarn over NPM

### LINKED ISSUE #1343: Update Campaign build to use Yarn not NPM
Aiming to speed up the build process by using Yarn over NPM

### PR DESCRIPTION
**Pull request by AndyEPhipps**
Type: patch

Fixes #1343 

## Changes proposed in this PR

- Adds Yarn to deps, allowing us to use it to build theme rather than the slower NPM

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Need to suss out what the Travis fail is all about, but it builds fine.. once I found out how to add Yarn to the platform.sh config file!

**Comment by AndyEPhipps** [comment]
Okay, since SR18 is currently using the NPM-flavoured version of Campaign ([and the build is failing](https://github.com/comicrelief/sr18/pull/279)), I think this needs to be merged in first.

[QA-able here](https://pr-1344-kdldkqq-tx3mbsqmxtu74.eu.platform.sh/news), need need to compare with the current master build [here](https://develop-tx3mbsqmxtu74.eu.platform.sh/fundraise)

**Comment by pvhee** [comment]
Can you verify if this error is also appearing on Circle CI @AndyEPhipps?
```
Failed to create style directory:     
                                          public://styles/cr_370_wide/public/2  
                                          016-08   
```
This failed the Travis build

**Comment by AndyEPhipps** [comment]
@pvhee : CircleCI seems happy enough? https://circleci.com/gh/comicrelief/campaign/51

**Comment by pvhee** [comment]
Let's merge it in this - we need to clean up and remove Travis, added in https://github.com/comicrelief/campaign/issues/1345

**Pull request merged**
