### PR TITLE
[#1377] - Update cr_teaser

### LINKED ISSUE #1377: Add CTA description as optional field to content wall
Add a CTA description field so that screen readers can pick up additional descriptions of links when the CTA Text is not sufficiently descriptive enough.

Part of https://github.com/comicrelief/sr18/issues/216 

Acceptance criteria:
- [x] Additional field in the CMS for adding description to CTA (optional field) 
- [x] When description is added, screen reader should read the additional description 
- [ ] When no description is added, the screen reader should read that the link in internal / opens in new tab

### PR DESCRIPTION
**Pull request by Saphyel**
Type: patch

Fixes #1377

### CODE REVIEW

**Comment by Heleen-cr** [comment]
@Saphyel @andy I think the aria-label attribute is better supported than the title attribute and I think that the aria-label replaces the anchor text when it comes to screen readers right?

**Comment by Heleen-cr** [comment]
@AndyEPhipps @Saphyel 
The result of using the aria-label though is that the description given in the aria-label is replacing the anchor tag's text. Which normally is fine, but in this case the h3 sits inside the anchor tag, so the description better be very descriptive as it's now the only info you have about the link.
What do you guys think?

**Comment by AndyEPhipps** [comment]
@Heleen-cr: not sure what you mean; def better to use the aria-label by the sounds of it.. and because it's a manually-inputted value, it can be whatever it needs to be, to make it as descriptive and useful as possible?

**Comment by Heleen-cr** [comment]
@AndyEPhipps  what I mean is that the aria-label replaces everything inside the <a></a>. So in this case that means also any headings that sit in it (since the whole teaser block is clickable the anchor tags are placed around all the content)
Not sure if this is what we want, but I guess if the description is descriptive enough it shouldn't matter?

**Pull request merged**
